---
all:
  hosts:
    mac:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3

  children:
    playgrounds:
      hosts:
        centos:
          ansible_host: python-server
        ubuntu:
          ansible_host: ubuntu-server
          ansible_python_interpreter: /usr/bin/python3