---
working_dir: ~/Project

service_list:
  - apache
  - nfs
  - mariadb

share_paths:
  nfs: /mnt/nfs
  cifs: /mnt/cifs
  iscsi: /mnt/iscsi
  work: "{{ working_dir }}"

distribution:
  centos:
    apache_pkg: httpd
  ubuntu:
    apache_pkg: apache2
