---
- hosts: mac
  gather_facts: yes
  # vars_files:
  #   - keys_vars.yml

  tasks:
    - name: Change instance state by tag
      ec2:
        # aws_access_key: "{{ AWS_ACCESS_KEY }}"
        # aws_secret_key: "{{ AWS_SECRET_KEY }}"
        # ec2_region: "{{ AWS_REGION }}"
        state: running
        instance_tags:
          Name: Demo