# AWS account variables are stored separately in a local secrets file
# The secrets file must be sourced into the shell before running the playbook
# Ensure that ansible_connection is set to local for localhost in the inventory
# My localhost is aliased to "mac"
# ENV variables in the file:
# - AWS_ACCESS_KEY
# - AWS_SECRET_KEY
# - AWS_REGION
---
- hosts: mac
  gather_facts: no
  tasks:
    - name: Change keypair permissions
      file:
        path: "{{ ssh_key_file }}"
        mode: '400'

    - name: Provision EC2
      ec2:
        instance_type: t2.micro
        keypair: ansible-ec2
        image: ami-0a887e401f7654935 # amzn2-ami-hvm-2.0.20200207.1-x86_64-gp2
        assign_public_ip: yes
        group: SSHAccess
        vpc_subnet_id: subnet-0302f8a86f4abae6f
        wait: yes
        exact_count: 1
        count_tag:
          Name: BuiltWithAnsible
        instance_tags:
          Name: BuiltWithAnsible
      register: ec2
    - debug:
        var: ec2

    - name: Add EC2 hosts to inventory
    # This adds the hosts to the playbook's in-memory inventory
      add_host:
        hostname: "{{ item.public_ip }}" # may also be .public_dns_name
        groupname: ec2instances
        ansible_user: ec2-user
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible_ssh_private_key_file: "{{ ssh_key_file }}"
      loop: "{{ ec2.instances }}"

- hosts: ec2instances
  gather_facts: no
  tasks:
    - name: Wait for SSH connection
      wait_for_connection:
        delay: 5
        timeout: 90

    - name: Check connection status
      ping:
