---
- hosts: playgrounds
  become: yes
  tasks:
    - name: Install eLinks
      package:
        name: elinks
        state: latest

- hosts: centos
  become: yes
  tasks:
    - name: Install Apache on CentOS
      package:
        name: httpd
        state: latest
        use: yum

- hosts: ubuntu
  become: yes
  tasks:
    - name: Install Apache on Ubuntu
      package:
        name: apache2
        state: latest
        use: apt