---
- hosts: playgrounds
  become: yes
  tasks:
    - name: Install eLinks
      package:
        name: elinks
        state: latest

- hosts: centos
  become: yes
  tasks:
    - name: Install Apache on CentOS
      package:
        name: "{{ apache_pkg }}"
        state: latest

- hosts: ubuntu
  become: yes
  tasks:
    - name: Install Apache on Ubuntu
      package:
        name: "{{ apache_pkg }}"
        state: latest